# Generated by Django 5.2.7 on 2025-11-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_rename_rutina_rutinas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Ejercicio')),
                ('descripcion', models.TextField(verbose_name='Descripción o Instrucciones')),
                ('categoria', models.CharField(choices=[('Pecho', 'Pecho'), ('Espalda', 'Espalda'), ('Pierna', 'Pierna'), ('Hombro', 'Hombro'), ('Brazo', 'Brazo'), ('Cardio', 'Cardio'), ('Abdominal', 'Abdominal'), ('Estiramiento', 'Estiramiento')], default='Pecho', max_length=50, verbose_name='Categoría Muscular')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Enlace de Video (URL)')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
            },
        ),
    ]
