# Generated by Django 5.2.7 on 2025-11-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0003_ejercicio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ejercicio',
            new_name='Ejercicios',
        ),
    ]
