# Generated by Django 5.2.7 on 2025-11-02 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0004_rename_ejercicio_ejercicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(help_text='El peso utilizado para el ejercicio.', verbose_name='Peso (kg o lbs)')),
                ('repeticiones', models.IntegerField(verbose_name='Repeticiones')),
                ('series', models.IntegerField(verbose_name='Series')),
                ('descanso', models.IntegerField(help_text='Tiempo de descanso entre series.', verbose_name='Descanso (minutos)')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='rutinas.ejercicios', verbose_name='Ejercicio Asociado')),
            ],
            options={
                'verbose_name': 'Detalle de Ejercicio',
                'verbose_name_plural': 'Detalles de Ejercicios',
            },
        ),
    ]
