# Generated by Django 5.2.7 on 2025-11-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0007_rutina'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutinaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Día de la Semana')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden del Ejercicio en el Día')),
                ('detalle_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_asociadas', to='rutinas.detalleejercicio', verbose_name='Detalle del Ejercicio (Peso/Reps)')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_rutina', to='rutinas.rutina', verbose_name='Rutina Base')),
            ],
            options={
                'verbose_name': 'Ejercicio Asignado por Día',
                'verbose_name_plural': 'Ejercicios Asignados por Día',
                'ordering': ['rutina', 'dia_semana', 'orden'],
                'unique_together': {('rutina', 'detalle_ejercicio', 'dia_semana')},
            },
        ),
    ]
