# Generated by Django 5.2.7 on 2025-11-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0008_rutinadia'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='activo',
            field=models.BooleanField(default=False, help_text='Indica si esta es la rutina que el usuario está siguiendo actualmente.'),
        ),
    ]
