# Generated by Django 5.2.7 on 2025-10-29 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaCorporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('pecho', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('brazo', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('brazo_der', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('antebrazo', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('antebrazo_der', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cintura', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('pierna_izq', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('pierna_der', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('gemelos', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('gemelos_izq', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cuello', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medida Corporal',
                'verbose_name_plural': 'Medidas Corporales',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
